apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: dev-ops
spec:
  ports:
    - port: 9090
      name: prometheus-port
      nodePort: 32090
      protocol: TCP
      targetPort: 9090
  selector:
    k8s-app: prometheus
  type: NodePort